### ISSUE TITLE
Performance statistics

### ISSUE THREAD

**Issue by gwicke** [gwicke/testreduce#21]
- Backend implementation for [perf stats](http://parsoid.wmflabs.org:8001/perfstats)
- front-end view for them (could also be tackled independently)

The current MySQL-based view supports ordering by arbitrary columns. This will be harder in cassandra, so we need to think about the actual use cases and maybe implement them in an optimized way. We generally use perf stats to:
- identify the slowest <n> pages
- identify the largest pages
- (ideally) calculate average timings / sizes per commit, so that we can establish longer-term performance trends

This information is contained in the result XML, and needs to be extracted from it when a result is added with addResult. The MySQL server already has code for the extraction, which can be moved to a method in the backend which is called from addResult.

It would be good to sketch a table layout for those stats first, based on the queries described above.

Who: Brando; 
also potentially interested: Krishnan, Collin, Lynn(would like to contribute to front-end view if that’s okay), Junjun

**Comment by gwicke** [comment]
@brando90, please start to sketch a design / ask questions here!

**Comment by brando90** [comment]
Hey Gabriel,

I was working on the cql tutorial you suggested me to do and was wondering, if there is any other thing you want me to learn or go through that you think would be useful for the part that corresponds to me before we talk about it on Monday, I think it would be very useful so that we don’t have to spend time on that on Monday.

Even if its things you find trivial, making sure I have it solid by Monday, I feel would be useful.

Also, if you want me to make sure I am familiar with some particular code, feel free to tell me and I will spend time going over it and stuff.

Thanks and see you Monday!

Hope you have fun skiing!

Regards, Brando Miranda

**Comment by brando90** [comment]
> Also, if you want me to make sure I am familiar with some particular
> code, feel free to tell me and I will spend time going over it and stuff.

I think looking at the current schema and the Cassandra backend should
be useful. Also interesting is Sebastian's pull request, which I hope
can land over the weekend.

You should start to think through the problem and maybe also sketch some
initial plan and Cassandra schema. You can also create a test table and
experiment with the queries you plan to run on them in cqlsh.

(replied via mail, odd that your name is shown as the author -- Gabriel)

**Comment by brando90** [comment]
Hi Gabriel!

My first doubt is, how do I get the raw data and what raw data do I get for tests? If I knew this it might be easier to start making a plan.

I am on irc most of the time so we can discuss thins there if you want/can! 

BM

**Comment by brando90** [comment]
Do I just assume that the data I need is already in the tables as specified by create_everything.cql ?

Like, there is a results table and one of its columns has a result column and is of type text, is there a format for that text or do I need to parse it?

BM

**Comment by brando90** [comment]
So my first idea is to write node.js script that gets the corresponding data from the results table and parse if it needs to and then feed that information to the table I want to create that maps (pages, commits) to the time they took to be parsed (this table could be called slowest_tables). Then we could have cql sort it or have the table always sorted by how long they took. 

We could also have a separate table that maps a page name (or page identifier) to its size and call that the pages_size table or something. We could have this sorted by cql or as we insert things we could sort it or something.

I am actually not quite sure how the sorting works but fill me in on anything/comment anything you feel might be helpful. :)

Am I kind of in the right track?

**Comment by brando90** [comment]
Quick question, wehn all this was on sql, I am sure you still computed all of the results in http://parsoid.wmflabs.org:8001/perfstats?orderby=size:htmlgzip
, I was wondering if I could maybe see those scripts to see if Im on the right track, or maybe I should completely disregard any old scripts we had for sql?

**Comment by brando90** [comment]
One important question, I just realized are the names of the pages inside of the test column in the results table?

**Comment by gwicke** [comment]
The json blob describing the test is in the test column. The backend should not care about the format / contents of the test description.

**Comment by brando90** [comment]
IDEA FOR ORDERING PERFORMANCE STATISTICS:

I have done some research about how we want to store the data for each performance statistics (like identifying the slowest pages or the largest ones) and there seems to be an option for Cassandra where we can create a keyspace/table with the following turned on: OrderPreservingPartitioner

If we do that I believe the Cassandra nodes orders the rows according to some key/value. However, it seems it has its drawbacks as pointed out by the following link:

http://ria101.wordpress.com/2010/02/22/cassandra-randompartitioner-vs-orderpreservingpartitioner/

Some of the main advantages/drawbacks I picked up were:

Advantage:
-you can perform range slices
-that is you can scan over ranges of your rows as though you were moving a cursor through a traditional index.

Drawback:
-the load balancing might not be good (which is bad because one node might become overloaded and queries to it might be slow, I believe)
-if we want to change back to a different type of partition like RandomPartitioner, all the data will be  have to be delete.

Some ideas to think about.

**Comment by brando90** [comment]
After doing a little research it seems that OrderPreservingPartitioner was deprecated...according to:

http://www.datastax.com/docs/1.1/configuration/node_configuration#partitioner

I guess I will think of something else.

**Comment by brando90** [comment]
Where is add result defined?

**Comment by brando90** [comment]
@gwicke  , at the top of the page you have a link to [perf stats](http://parsoid.wmflabs.org:8001/perfstats)
I was wondering, my page does not open anything and I think it would be nice to see it, how do I make that link work?

**Comment by brando90** [comment]
Hi @gwicke 

How is a result added? I am just confused because I would like to insert some dummy stuff in the code and play with it to see how things work but I am having trouble inserting/creating dummy results XML.

**Comment by brando90** [comment]
Hi @gwicke ,

just finished doing the top slowest and largest. I think you mentioned @choucalate already did the other part of the task, right? 

Unless we need to change the implementation I already did, I think its ok to close this issue? Unless there is something else we need for it. Or we can just open a new too.
